/**
 * `agentic-runlet` — the run shim (TD-025 §1, technical/05 § "Control channel").
 *
 * It is the entrypoint of the run container. It listens on two Unix sockets on the per-run control
 * volume and owns exactly one child: the Claude Code CLI.
 *
 *   `/ctl/ctl.sock`   the **control** socket. One authenticated connection, ever. The runner
 *                     spawns, writes stdin, relays signals and reads stdout/stderr/exit over it.
 *   `/ctl/cred.sock`  the **credential** socket. The workspace's git credential helper asks for a
 *                     token here; the shim forwards the question and relays the answer.
 *
 * ## The trust boundary, stated honestly
 *
 * The token in `hello` authenticates **the runner to the shim across the control volume** — the
 * volume is shared with the launcher and, at TD-025's layout, one directory per run, so the token
 * is what stops another run's runner (or anything else that can see the volume) from driving this
 * shim. It does **not** authenticate the shim against its own child, and nothing inside one
 * container can: the CLI runs as the same uid as the shim, so it can read `/proc/<shim>/environ`,
 * the token file on `/ctl`, and in most configurations the shim's memory. Treating the token as a
 * secret *from the agent* would be theatre.
 *
 * What actually keeps a compromised child off the control channel is the **single connection**,
 * and it is a structural property rather than a check: the runner connects at run start, before
 * `spawn` — that is, before the child exists at all — and from that moment every further connection
 * is refused unread. If the control connection ever drops, the shim kills the child and exits, so
 * the slot is never free while a child is alive. The credential socket is therefore the only
 * surface the workspace can reach, which is why its policy (below) is the part with teeth.
 *
 * ## What a compromised child can ask for, and what it cannot
 *
 * It can ask for a credential for **one lowercase DNS host over https**, at most
 * {@link RunletShimOptions.maxCredentialRequests} times per run, at most
 * {@link RunletShimOptions.maxConcurrentCredentials} at a time, and only while a child is
 * *running* — which is a stronger statement than "a child was spawned", and the difference was a
 * live defect: see `childIsRunning`, which reads the child's exit status rather than the fact that
 * a child object exists. That is the entire surface. It cannot:
 *
 *  - ask over cleartext — `cred.get.protocol` has one value, so an `http://` helper invocation
 *    cannot produce a frame that parses;
 *  - name another request — the `request_id` that reaches the runner is generated by the shim, and
 *    a reply is delivered only to the connection whose question it answers;
 *  - use the channel as an oracle or a denial of service — the caps above are counted per run and
 *    a refusal is a `fatal`, not a retry;
 *  - reach anything else on the socket — the credential connection accepts `cred.get` and `ping`
 *    and refuses every other frame, `spawn` included;
 *  - learn *which* hosts are allowed from the shim, because **the shim holds no allow-list and no
 *    credential**. The decision is the runner's (`spawn-adapter.ts`), on the platform side of the
 *    volume, where the agent cannot read it. A policy stored in the container is a policy the
 *    container can be made to lie about.
 *
 * ## Time
 *
 * Every deadline — the handshake window, the kill grace period, the credential timeout, the stdio
 * flush after exit — is measured on the injected {@link RunnerClock} (standing rule 2). The tests
 * advance it by hand; nothing here waits on a wall clock.
 */
import { type ChildProcess, spawn as spawnChildProcess } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { chmod, lstat } from 'node:fs/promises';
import { createServer, type Server, type Socket } from 'node:net';
import type { Readable } from 'node:stream';
import { type Logger, type RunnerClock, silentLogger } from '@platform/application';
import type { RunletFatalReason, RunletFrame } from '@platform/contracts';
import { RUNLET_PROTOCOL_VERSION } from '@platform/contracts';
import { createFrameConnection, type FrameConnection } from './connection.js';
import { type DecodedFrame, MAX_FRAME_PAYLOAD_BYTES, RunletProtocolError } from './framing.js';
import { tokensMatch, validateRunToken } from './token.js';

/** What `spawn` is allowed to start, injected so a test can watch the arguments without a fork. */
export type SpawnChild = (
  command: string,
  args: readonly string[],
  options: {
    cwd: string;
    env: Record<string, string>;
    stdio: ['pipe', 'pipe', 'pipe'];
    shell: false;
    windowsHide: true;
    uid?: number;
    gid?: number;
  },
) => ChildProcess;

export interface RunletShimOptions {
  /** Runner-facing socket. Refuses to start if the path already exists. */
  readonly controlSocketPath: string;
  /** Workspace-facing credential socket. Omit to run a shim with no credential channel at all. */
  readonly credentialSocketPath?: string | null;
  /** The run token. Empty, blank or too short is refused at construction (standing rule 18). */
  readonly token: string;
  readonly clock: RunnerClock;
  readonly logger?: Logger;
  /** SIGTERM → this long → SIGKILL, when the control connection drops (TD-025 §1). */
  readonly killGraceMs?: number;
  /** A connection that has not said `hello` in this long is dropped. */
  readonly handshakeTimeoutMs?: number;
  /** How long the runner has to answer a `cred.get` before the child is told "no credential". */
  readonly credentialTimeoutMs?: number;
  /** After the child exits, wait at most this long for its stdio to drain before `exit`. */
  readonly stdioFlushMs?: number;
  readonly maxCredentialRequests?: number;
  readonly maxConcurrentCredentials?: number;
  /** Failed handshakes before the shim stops listening. The window is before the child exists. */
  readonly maxFailedHandshakes?: number;
  /** uid/gid for the child. Required when the shim itself is root; ignored otherwise. */
  readonly childUid?: number | null;
  readonly childGid?: number | null;
  readonly spawnChild?: SpawnChild;
  readonly currentUid?: () => number | undefined;
  /** Called once, when the shim has finished shutting down. The entrypoint exits the process. */
  readonly onShutdown?: (reason: RunletShutdownReason) => void;
}

export type RunletShutdownReason =
  | 'child_exited'
  | 'control_disconnected'
  | 'handshake_attempts_exhausted'
  | 'closed';

export interface RunletShimMetrics {
  /** How often the control socket's buffer filled and the child's stdout was paused. */
  readonly stdoutPauses: number;
  readonly stderrPauses: number;
  readonly credentialRequests: number;
  readonly credentialRefusals: number;
  /** `cred.reply`s naming a request that had already timed out or never existed. */
  readonly staleCredentialReplies: number;
  readonly rejectedConnections: number;
  readonly failedHandshakes: number;
  /**
   * Every signal the shim sent the child *on its own initiative*, in order — the teardown
   * sequence, never the ones the runner asked for.
   *
   * It exists because the grace period cannot be observed any other way. Process death is
   * asynchronous at the operating system's convenience, so "the child is still alive one
   * millisecond before the grace expires" is not a fact a test can assert; a mutation that sent
   * SIGKILL immediately survived a test that tried. What *is* deterministic is what the shim did:
   * `['SIGTERM']` before the grace, `['SIGTERM', 'SIGKILL']` after. The process-state assertion
   * beside it then proves the SIGKILL was real rather than merely recorded (standing rule 29:
   * the counter a test believes must itself be seen to move).
   */
  readonly teardownSignals: readonly string[];
}

export interface RunletShim {
  start(): Promise<void>;
  close(): Promise<void>;
  readonly metrics: RunletShimMetrics;
  readonly childPid: number | null;
}

const DEFAULTS = {
  killGraceMs: 10_000,
  handshakeTimeoutMs: 30_000,
  credentialTimeoutMs: 30_000,
  stdioFlushMs: 2_000,
  maxCredentialRequests: 32,
  maxConcurrentCredentials: 4,
  maxFailedHandshakes: 3,
} as const;

/** Frames the runner may send, by shim state. Parsing says well-formed; this says allowed. */
const CONTROL_ACCEPTS: Readonly<Record<'awaiting_hello' | 'ready' | 'running', readonly string[]>> =
  {
    awaiting_hello: ['hello'],
    ready: ['spawn', 'ping'],
    running: ['stdin', 'stdin.end', 'signal', 'cred.reply', 'ping'],
  };

/** Frames the workspace may send on the credential socket. Everything else is refused. */
const CREDENTIAL_ACCEPTS: readonly string[] = ['cred.get', 'ping'];

interface PendingCredential {
  readonly connection: FrameConnection;
  readonly childRequestId: string;
  readonly cancelTimeout: () => void;
}

/** A `fatal` for a socket that never got a decoder — a refusal must still say why. */
const encodeFatal = (reason: RunletFatalReason, message: string): Buffer => {
  const header = Buffer.from(JSON.stringify({ type: 'fatal', reason, message }), 'utf8');
  const prefix = Buffer.allocUnsafe(8);
  prefix.writeUInt32BE(header.length, 0);
  prefix.writeUInt32BE(0, 4);
  return Buffer.concat([prefix, header]);
};

export const createRunletShim = (options: RunletShimOptions): RunletShim => {
  const logger = options.logger ?? silentLogger;
  const clock = options.clock;
  const killGraceMs = options.killGraceMs ?? DEFAULTS.killGraceMs;
  const handshakeTimeoutMs = options.handshakeTimeoutMs ?? DEFAULTS.handshakeTimeoutMs;
  const credentialTimeoutMs = options.credentialTimeoutMs ?? DEFAULTS.credentialTimeoutMs;
  const stdioFlushMs = options.stdioFlushMs ?? DEFAULTS.stdioFlushMs;
  const maxCredentialRequests = options.maxCredentialRequests ?? DEFAULTS.maxCredentialRequests;
  const maxConcurrentCredentials =
    options.maxConcurrentCredentials ?? DEFAULTS.maxConcurrentCredentials;
  const maxFailedHandshakes = options.maxFailedHandshakes ?? DEFAULTS.maxFailedHandshakes;
  const spawnChild = options.spawnChild ?? (spawnChildProcess as unknown as SpawnChild);
  const currentUid = options.currentUid ?? (() => process.getuid?.());

  // Standing rule 18: an empty credential is not a credential. This throws rather than warns, so a
  // shim can never be listening with a token that matches whatever an attacker sends.
  const token = validateRunToken(options.token);

  let controlServer: Server | null = null;
  let credentialServer: Server | null = null;
  let control: FrameConnection | null = null;
  let controlState: 'awaiting_hello' | 'ready' | 'running' = 'awaiting_hello';
  /** True from the first successful `hello` — for ever. The slot is never given back. */
  let controlTaken = false;
  let child: ChildProcess | null = null;
  let childExit: { code: number | null; signal: string | null } | null = null;
  let exitReported = false;
  let shuttingDown = false;
  let credentialCount = 0;
  const pending = new Map<string, PendingCredential>();
  const credentialConnections = new Set<FrameConnection>();
  const metrics = {
    stdoutPauses: 0,
    stderrPauses: 0,
    credentialRequests: 0,
    credentialRefusals: 0,
    staleCredentialReplies: 0,
    rejectedConnections: 0,
    failedHandshakes: 0,
    teardownSignals: [] as string[],
  };

  // ── the child ──────────────────────────────────────────────────────────────

  const chunk = (buffer: Buffer): Buffer[] => {
    if (buffer.length <= MAX_FRAME_PAYLOAD_BYTES) {
      return [buffer];
    }
    const slices: Buffer[] = [];
    for (let at = 0; at < buffer.length; at += MAX_FRAME_PAYLOAD_BYTES) {
      slices.push(buffer.subarray(at, at + MAX_FRAME_PAYLOAD_BYTES));
    }
    return slices;
  };

  const paused = new Set<Readable>();

  let cancelFlush: (() => void) | null = null;

  /**
   * The window between the child's `exit` and its stdio's `close`, and what it is a bound *on*.
   *
   * `close` is the honest end of the run: it means every byte the child wrote has been read and
   * framed. A detached grandchild holding the pipe can withhold it for ever, so a bound is needed —
   * but the bound must be on **silence**, not on how long the tail takes to arrive. A single
   * deadline armed at `exit` cuts off a stream that is still delivering, and the loss is silent: a
   * 16 MiB conformance run lost its last pipe read (**65,536 bytes** — exactly one 64 KiB pipe
   * buffer, taking the `result` line with it) whenever a loaded machine made the drain outlast the
   * two-second default. Every frame forwarded after the child is gone therefore re-arms it.
   *
   * The trade this makes, stated plainly: a grandchild that keeps writing keeps the shim alive. The
   * run's own deadline is the platform's (WP-12's wall-clock budget) and the container's stop is
   * WP-14's; neither belongs in a timer here, and a shim that silently drops the end of the agent's
   * output is the worse failure of the two.
   */
  const armStdioFlush = (): void => {
    if (childExit === null || exitReported) {
      return;
    }
    cancelFlush?.();
    cancelFlush = clock.setTimer(stdioFlushMs, reportExit);
  };

  const pipeToFrames = (stream: Readable, type: 'stdout' | 'stderr'): void => {
    stream.on('data', (data: Buffer) => {
      let writable = true;
      for (const slice of chunk(data)) {
        writable = (control?.send({ type }, slice) ?? false) && writable;
      }
      // Progress after the child is gone: the flush window is a bound on *silence*, not on how long
      // the tail takes to drain. See `armStdioFlush`.
      armStdioFlush();
      if (!writable && !paused.has(stream)) {
        // The socket buffer is full. Stop reading the child rather than growing an unbounded queue
        // in this process — the child's own pipe then applies the backpressure to the CLI itself.
        paused.add(stream);
        stream.pause();
        if (type === 'stdout') {
          metrics.stdoutPauses += 1;
        } else {
          metrics.stderrPauses += 1;
        }
      }
    });
  };

  const resumeStreams = (): void => {
    for (const stream of paused) {
      stream.resume();
    }
    paused.clear();
  };

  /**
   * Is there a child *running*, right now?
   *
   * `child !== null` is not that question. `child` is set by `spawn` and never cleared, so it stays
   * true through the whole window between the child's exit and the shim's teardown — at least
   * `stdioFlushMs`, and **unbounded** when a grandchild holds the stdout pipe open, because `close`
   * is what ends the run and `close` waits for the pipe. A review round drove exactly that: a child
   * forked a grandchild holding stdout and exited 7, and a `cred.get` arriving in the window was
   * forwarded to the runner with no `exit` frame yet sent.
   *
   * Node sets `exitCode` (or `signalCode`, for a child that was signalled — the two are exclusive,
   * so both must be read) in the handle's `onexit`, before it emits `exit`. Reading them closes the
   * window at the first instant the shim can know the child is gone.
   */
  const childIsRunning = (): boolean =>
    child !== null && child.exitCode === null && child.signalCode === null;

  const reportExit = (): void => {
    if (exitReported || childExit === null) {
      return;
    }
    exitReported = true;
    control?.send({ type: 'exit', code: childExit.code, signal: childExit.signal });
    beginShutdown('child_exited');
  };

  const refuseSpawn = (message: string): void => {
    logger.warn({ reason: 'spawn_refused', message }, 'runlet refused a spawn');
    control?.fail('spawn_refused', message);
  };

  const startChild = (frame: Extract<RunletFrame, { type: 'spawn' }>): void => {
    const uid = currentUid();
    if (uid === 0 && (options.childUid === undefined || options.childUid === null)) {
      // TD-025 §1: the child runs as uid 1000. If the shim is root and nobody said which uid to
      // drop to, running the agent's CLI as root is the one outcome that must not happen quietly.
      refuseSpawn('the shim is running as root and no child uid was configured');
      return;
    }
    const spawnOptions = {
      cwd: frame.cwd,
      // technical/04: `env` replaces, never merges. The shim's own environment carries the run
      // token; merging it would hand the token to the CLI for no reason at all.
      env: { ...frame.env },
      stdio: ['pipe', 'pipe', 'pipe'] as ['pipe', 'pipe', 'pipe'],
      shell: false as const,
      windowsHide: true as const,
      ...(options.childUid === undefined || options.childUid === null
        ? {}
        : { uid: options.childUid }),
      ...(options.childGid === undefined || options.childGid === null
        ? {}
        : { gid: options.childGid }),
    };

    let started: ChildProcess;
    try {
      started = spawnChild(frame.command, frame.args, spawnOptions);
    } catch (error) {
      refuseSpawn(`the child could not be started: ${(error as Error).message}`);
      return;
    }
    child = started;
    controlState = 'running';

    started.on('error', (error) => {
      logger.error({ err: error }, 'runlet child failed to start');
      childExit = { code: null, signal: null };
      // A spawn that never produced a process still has to reach the runner as an end of the run:
      // an `exit` frame it can read, not a socket that goes quiet.
      if (!exitReported) {
        exitReported = true;
        control?.send({ type: 'exit', code: null, signal: null });
        beginShutdown('child_exited');
      }
    });
    if (started.stdout !== null) {
      pipeToFrames(started.stdout, 'stdout');
    }
    if (started.stderr !== null) {
      pipeToFrames(started.stderr, 'stderr');
    }
    started.on('exit', (code, signal) => {
      childExit = { code, signal };
      // `close` (all stdio ended) is what guarantees the tail of stdout has been framed; a
      // grandchild holding the pipe can delay it for ever, so the flush window is the backstop.
      armStdioFlush();
    });
    started.on('close', () => {
      cancelFlush?.();
      cancelFlush = null;
      reportExit();
    });

    const pid = started.pid;
    if (pid !== undefined) {
      control?.send({ type: 'spawn.ok', pid });
    }
    logger.info({ command: frame.command, cwd: frame.cwd, pid: pid ?? null }, 'runlet spawned');
  };

  // ── shutdown ───────────────────────────────────────────────────────────────

  /**
   * Teardown, and the exact width of its guarantee.
   *
   * What this guarantees: **the child the shim spawned** is sent SIGTERM, and SIGKILL if it is
   * still alive {@link RunletShimOptions.killGraceMs} later. Nothing more. `kill` names one pid, so
   * a process the child *detached* — `setsid`, a double fork, `spawn(…, { detached: true })` —
   * outlives this. A reviewer verified it with `process.kill(pid, 0)`: the grandchild was still
   * there after the shim had shut down.
   *
   * What makes that acceptable is a property of the *container*, not of this file: the run's whole
   * pid namespace dies when the container stops, so an escaped grandchild lives exactly as long as
   * the container does (`docs/research/12-run-shim-verification.md` §6, "a runner that disappears
   * leaves no agent behind", where the run container reached `exited:0` — the last of the seven
   * checks that script records). That makes stopping the container **WP-14's** obligation, not an
   * optimisation: a launcher that removes the control volume and leaves the container running would
   * leave the agent's grandchildren running with it. Signalling the process *group* from here is not
   * the fix it looks like: `detached: true` is precisely a request for a **new** process group
   * (measured — a plain child shares the shim's pgid, a detached one gets its own), so a group
   * signal would miss the one process that escaped and hit the shim's own group instead.
   */
  const killChild = (): void => {
    const target = child;
    if (target === null || target.exitCode !== null || target.signalCode !== null) {
      return;
    }
    metrics.teardownSignals.push('SIGTERM');
    target.kill('SIGTERM');
    const cancel = clock.setTimer(killGraceMs, () => {
      if (target.exitCode === null && target.signalCode === null) {
        logger.warn({ pid: target.pid ?? null }, 'runlet child ignored SIGTERM; sending SIGKILL');
        metrics.teardownSignals.push('SIGKILL');
        target.kill('SIGKILL');
      }
    });
    target.once('exit', cancel);
  };

  function beginShutdown(reason: RunletShutdownReason): void {
    if (shuttingDown) {
      return;
    }
    shuttingDown = true;
    logger.info({ reason }, 'runlet shutting down');
    for (const [, entry] of pending) {
      entry.cancelTimeout();
      entry.connection.fail('shutting_down', 'the run is over');
    }
    pending.clear();
    for (const connection of credentialConnections) {
      connection.close();
    }
    credentialConnections.clear();
    credentialServer?.close();
    if (reason === 'control_disconnected') {
      killChild();
    }
    const running = child;
    if (reason !== 'control_disconnected' || running === null || !childIsRunning()) {
      // `child === null` was the condition here too, and it is the same mistake: a child that has
      // already exited will never emit `exit` again, so the shim waited for an event that could
      // not arrive and stayed alive with both servers listening. An orphaned shim holding a run's
      // control volume is the failure TD-025 §1 is about, reached from the other end.
      controlServer?.close();
      control?.close();
      options.onShutdown?.(reason);
      return;
    }
    // Wait for the child to be gone before the process may exit: an orphaned agent is exactly what
    // TD-025 §1 forbids. Reached only while the child is still running, so the event is still to
    // come.
    running.once('exit', () => {
      controlServer?.close();
      control?.close();
      options.onShutdown?.(reason);
    });
  }

  // ── the control connection ─────────────────────────────────────────────────

  const handleControlFrame = (decoded: DecodedFrame, connection: FrameConnection): void => {
    const { frame, payload } = decoded;
    if (!CONTROL_ACCEPTS[controlState].includes(frame.type)) {
      throw new RunletProtocolError(
        `a ${frame.type} frame arrived while the shim was ${controlState}`,
        controlState === 'awaiting_hello' ? 'auth_failed' : 'unexpected_frame',
      );
    }
    switch (frame.type) {
      case 'hello': {
        if (frame.protocol !== RUNLET_PROTOCOL_VERSION) {
          throw new RunletProtocolError(
            `the runner speaks protocol ${frame.protocol}, the shim speaks ${RUNLET_PROTOCOL_VERSION}`,
            'auth_failed',
          );
        }
        if (!tokensMatch(token, frame.token)) {
          throw new RunletProtocolError('the run token did not match', 'auth_failed');
        }
        controlTaken = true;
        controlState = 'ready';
        connection.send({ type: 'hello.ok', protocol: RUNLET_PROTOCOL_VERSION });
        logger.info({}, 'runlet control connection authenticated');
        return;
      }
      case 'spawn':
        startChild(frame);
        return;
      case 'stdin':
        child?.stdin?.write(payload as Buffer);
        return;
      case 'stdin.end':
        child?.stdin?.end();
        return;
      case 'signal':
        child?.kill(frame.name);
        return;
      case 'cred.reply': {
        const entry = pending.get(frame.request_id);
        if (entry === undefined) {
          // A reply to a request that has already timed out, or one nobody asked. Dropping it is
          // the fail-closed answer: the child is told "no credential" by the timeout path.
          metrics.staleCredentialReplies += 1;
          logger.warn({ request_id: frame.request_id }, 'runlet dropped a stale cred.reply');
          return;
        }
        pending.delete(frame.request_id);
        entry.cancelTimeout();
        entry.connection.send({
          type: 'cred.reply',
          request_id: entry.childRequestId,
          credential: frame.credential,
        });
        return;
      }
      case 'ping':
        connection.send({ type: 'pong' });
        return;
      default:
        throw new RunletProtocolError(
          `the shim does not accept a ${frame.type} frame`,
          'unexpected_frame',
        );
    }
  };

  const onControlConnection = (socket: Socket): void => {
    if (controlTaken || control !== null || shuttingDown) {
      metrics.rejectedConnections += 1;
      logger.warn({}, 'runlet refused a second control connection');
      // Refused unread: the frame decoder is never attached, so nothing this socket sends is
      // parsed, let alone acted on.
      socket.write(
        encodeFatal('connection_taken', 'the shim accepts exactly one control connection'),
      );
      socket.destroySoon();
      return;
    }
    let handshake: (() => void) | null = clock.setTimer(handshakeTimeoutMs, () => {
      handshake = null;
      logger.warn({}, 'runlet dropped a connection that never said hello');
      connection.fail('handshake_timeout', 'no hello inside the handshake window');
    });
    const connection: FrameConnection = createFrameConnection(socket, {
      onFrame: (decoded) => {
        if (decoded.frame.type === 'hello') {
          handshake?.();
          handshake = null;
        }
        handleControlFrame(decoded, connection);
      },
      onError: (error) => {
        const reason: RunletFatalReason =
          error instanceof RunletProtocolError ? error.reason : 'protocol_error';
        logger.warn({ reason, message: error.message }, 'runlet control connection failed');
        connection.fail(reason, error.message);
      },
      onClose: () => {
        handshake?.();
        handshake = null;
        if (control !== connection) {
          return;
        }
        control = null;
        if (controlTaken) {
          beginShutdown('control_disconnected');
          return;
        }
        // The connection went away without ever authenticating. Counting it here rather than in
        // `onError` counts every way it can fail — a bad token, a timeout, a peer that just left —
        // exactly once, which is what the attempt budget is about.
        metrics.failedHandshakes += 1;
        if (metrics.failedHandshakes >= maxFailedHandshakes) {
          logger.error({ attempts: metrics.failedHandshakes }, 'runlet stops listening');
          beginShutdown('handshake_attempts_exhausted');
        }
      },
      onDrain: resumeStreams,
    });
    control = connection;
  };

  // ── the credential connection ──────────────────────────────────────────────

  const refuseCredential = (connection: FrameConnection, message: string): void => {
    metrics.credentialRefusals += 1;
    logger.warn({ message }, 'runlet refused a credential request');
    connection.fail('credential_refused', message);
  };

  const handleCredentialFrame = (decoded: DecodedFrame, connection: FrameConnection): void => {
    const { frame } = decoded;
    if (!CREDENTIAL_ACCEPTS.includes(frame.type)) {
      throw new RunletProtocolError(
        `the credential socket does not accept a ${frame.type} frame`,
        'unexpected_frame',
      );
    }
    if (frame.type === 'ping') {
      connection.send({ type: 'pong' });
      return;
    }
    if (frame.type !== 'cred.get') {
      return;
    }
    if (control === null || controlState !== 'running' || !childIsRunning() || shuttingDown) {
      refuseCredential(connection, 'no run is active');
      return;
    }
    // The residual this guard leaves, stated rather than implied: it decides whether a request is
    // *accepted*, and a request accepted while the child was still running can still be *answered*
    // during the flush window — the runner's `cred.reply` arrives, `pending` still holds the entry,
    // and the credential goes to whoever holds that credential socket, which may by then be a
    // grandchild the child left behind. That is the same principal the run already trusted with the
    // token, over a socket it was already holding, so it is not an escalation; closing it would mean
    // dropping in-flight replies at the child's exit, which turns a normal race — the helper asks,
    // the CLI finishes — into a failed fetch. What must not happen is a *new* request being
    // accepted after the child is gone, and that is what the line above refuses.
    if (credentialCount >= maxCredentialRequests) {
      refuseCredential(connection, 'the run has used its credential requests');
      return;
    }
    if (pending.size >= maxConcurrentCredentials) {
      refuseCredential(connection, 'too many credential requests in flight');
      return;
    }
    credentialCount += 1;
    metrics.credentialRequests += 1;
    // Our id, not the child's: a request_id the workspace chose would let one helper name another
    // helper's pending question.
    const requestId = `c${credentialCount}-${randomUUID().slice(0, 8)}`;
    const cancelTimeout = clock.setTimer(credentialTimeoutMs, () => {
      pending.delete(requestId);
      logger.warn({ host: frame.host }, 'runlet credential request timed out');
      connection.send({ type: 'cred.reply', request_id: frame.request_id, credential: null });
    });
    pending.set(requestId, {
      connection,
      childRequestId: frame.request_id,
      cancelTimeout,
    });
    // Rebuilt from validated fields rather than forwarded: the frame that reaches the runner is the
    // shim's statement, not the workspace's.
    control.send({
      type: 'cred.get',
      request_id: requestId,
      host: frame.host,
      protocol: 'https',
    });
  };

  const onCredentialConnection = (socket: Socket): void => {
    if (shuttingDown) {
      socket.write(encodeFatal('shutting_down', 'the run is over'));
      socket.destroySoon();
      return;
    }
    if (credentialConnections.size >= maxConcurrentCredentials) {
      metrics.credentialRefusals += 1;
      socket.write(encodeFatal('credential_refused', 'too many credential connections'));
      socket.destroySoon();
      return;
    }
    const connection: FrameConnection = createFrameConnection(socket, {
      onFrame: (decoded) => handleCredentialFrame(decoded, connection),
      onError: (error) => {
        const reason: RunletFatalReason =
          error instanceof RunletProtocolError ? error.reason : 'protocol_error';
        logger.warn({ reason, message: error.message }, 'runlet credential connection failed');
        connection.fail(reason, error.message);
      },
      onClose: () => {
        credentialConnections.delete(connection);
        for (const [id, entry] of pending) {
          if (entry.connection === connection) {
            entry.cancelTimeout();
            pending.delete(id);
          }
        }
      },
    });
    credentialConnections.add(connection);
  };

  // ── lifecycle ──────────────────────────────────────────────────────────────

  const listen = async (server: Server, path: string): Promise<void> => {
    // Refusing an existing path rather than unlinking it: a socket already there means another shim
    // believes it owns this run, and taking it over silently is how two shims share one child.
    const existing = await lstat(path).catch(() => null);
    if (existing !== null) {
      throw new RunletProtocolError(`${path} already exists; refusing to take over a run`);
    }
    await new Promise<void>((resolve, reject) => {
      server.once('error', reject);
      server.listen(path, () => {
        server.off('error', reject);
        resolve();
      });
    });
    // 0600: the runner reaches this socket as the same uid (WP-14 wires the run container and the
    // runner container to one uid); nothing else on the volume may open it.
    await chmod(path, 0o600);
  };

  return {
    get metrics(): RunletShimMetrics {
      return { ...metrics, teardownSignals: [...metrics.teardownSignals] };
    },
    get childPid() {
      return child?.pid ?? null;
    },
    start: async () => {
      controlServer = createServer(onControlConnection);
      await listen(controlServer, options.controlSocketPath);
      if (options.credentialSocketPath !== undefined && options.credentialSocketPath !== null) {
        credentialServer = createServer(onCredentialConnection);
        await listen(credentialServer, options.credentialSocketPath);
      }
      logger.info(
        {
          control_socket: options.controlSocketPath,
          credential_socket: options.credentialSocketPath ?? null,
        },
        'runlet listening',
      );
    },
    close: async () => {
      shuttingDown = true;
      for (const [, entry] of pending) {
        entry.cancelTimeout();
      }
      pending.clear();
      for (const connection of credentialConnections) {
        connection.close();
      }
      credentialConnections.clear();
      control?.close();
      child?.kill('SIGKILL');
      await Promise.all(
        [controlServer, credentialServer].map(
          (server) =>
            new Promise<void>((resolve) => {
              if (server === null) {
                resolve();
                return;
              }
              server.close(() => resolve());
            }),
        ),
      );
      controlServer = null;
      credentialServer = null;
    },
  };
};
