/**
 * `Idempotency-Key` — technical/08 § "Principles", shared by every command route.
 *
 * It was WP-21's, inside `routes/onboarding.ts`, and it moved here when WP-15i added eleven more
 * commands: two copies of a key's character set, its cap and its digest would be two things to keep
 * true, and the second copy is the one that would silently accept a key the first refuses.
 *
 * ## What the header buys, and the two shapes it takes
 *
 * The mechanism is one **digest of the canonical request**, recorded in the `human_actions` row the
 * command writes ({@link recordHumanAction}) beside the key itself. `human_actions` is append-only
 * (`platform_table_policy`), one row is written per performed command, and that makes it the
 * idempotency store technical/08's header implies — with no new table and no migration.
 *
 * Two commands then read it differently, and the difference is the resource's, not the header's:
 *
 * - **A create with a natural key** (the wizard's three) answers a retry by re-reading the resource
 *   through `projects.key` or `(integrations.org_id, type, name)`. The digest is what turns a
 *   *different* body under a used key into a `409` rather than a silent replay.
 * - **A command with no natural key** (every task and run command) has nothing to re-read, so the
 *   recorded attempt **is** the answer: {@link idempotentReplay} reports that this key has already
 *   performed this command, the caller answers with the resource's current state and
 *   `performed: false`, and nothing is performed twice.
 *
 * There is still no stored *response* in either shape. A replay is answered by re-reading, which is
 * the same answer and one fewer thing to keep consistent.
 *
 * ## A key belongs to the caller
 *
 * Every lookup here is scoped to `(user_id, action, key)`. technical/08 says an `Idempotency-Key`
 * goes on a command a client may retry and does not say whose it is; the caller is the only honest
 * owner, because the string is generated by a client per attempt and nothing distinguishes one
 * client's `retry-1` from another's. An installation-wide lookup would answer this caller a
 * `409 idempotency_key_reused` for a key a stranger used — a wrong refusal, and an oracle for the
 * existence of somebody else's command. {@link findIdempotentAttempt} carries the full argument
 * and what the narrower scope gives up.
 *
 * ## The residual, which is the same one `findIdempotentAttempt` states
 *
 * Two requests from the same caller carrying the same key that arrive **at once** both read "no
 * previous attempt" before either commits (READ COMMITTED), so the second is not refused. For a wizard create the unique key
 * underneath still stops a second row. For a task command what bounds it is the aggregate and the
 * queue rather than this header: two concurrent `retry-stage` calls each move the attempt counter,
 * `tasks.version` makes one of them re-read (WP-15e), and the `stage.execute` queue is `stately` per
 * task with the executor re-validating the attempt — so the pair produces one extra attempt number
 * and **one** run. Closing it properly needs a unique index on
 * `(user_id, action, params->>'idempotency_key')` plus writing the row *before* the effect, which trades a
 * double-perform for a key that claims a command nobody performed; that is a different design and
 * it is in `PROGRESS.md`, not here.
 */
import { createHash } from 'node:crypto';
import type { JsonObject } from '@platform/contracts';
import type { FastifyRequest } from 'fastify';
import { HttpError } from '../errors.js';
import type { Database } from '../queries/identity-queries.js';
import { findIdempotentAttempt } from '../queries/onboarding-queries.js';

/** Longest `Idempotency-Key` this server stores in an audit row. */
export const MAX_IDEMPOTENCY_KEY_CHARS = 200;

/**
 * The key a client sent, or `null` when it sent none.
 *
 * Client-chosen text on its way to a `human_actions` row, so it is bounded and its character set is
 * fixed rather than escaped: a key is an identity, and anything outside the set is refused rather
 * than rewritten (the argument `idempotencyScopeFor` makes for a provider key, one layer out).
 */
export const readIdempotencyKey = (request: FastifyRequest): string | null => {
  const raw = request.headers['idempotency-key'];
  const value = Array.isArray(raw) ? raw[0] : raw;
  if (value === undefined || value.length === 0) {
    return null;
  }
  if (value.length > MAX_IDEMPOTENCY_KEY_CHARS || !/^[A-Za-z0-9._:-]+$/.test(value)) {
    throw new HttpError(
      400,
      'invalid_request',
      `the Idempotency-Key must be at most ${MAX_IDEMPOTENCY_KEY_CHARS} characters of A-Z a-z 0-9 . _ : -`,
    );
  }
  return value;
};

/** The same, for a command that **creates** and therefore requires the header. */
export const requireIdempotencyKey = (request: FastifyRequest): string => {
  const key = readIdempotencyKey(request);
  if (key === null) {
    throw new HttpError(
      400,
      'idempotency_key_required',
      'this command creates something, so it needs an Idempotency-Key header: send the same key when you retry (technical/08)',
    );
  }
  return key;
};

/**
 * Refuses a request that reuses a key with a **different** body, and passes anything else.
 *
 * The decision, separated from the read so it can be driven directly: it has three branches and
 * two of them are "do nothing", which is exactly the shape that reads as tested because the happy
 * path runs constantly (standing rule 67).
 *
 * The digest is over the canonical JSON of whatever the command considers its request — the body
 * for a create, the path's project for a command whose body is empty — so key ordering does not
 * make two identical requests look different (`configHashOf` uses the same serialiser and says
 * why).
 *
 * Absent is not an error: a key nobody has used is the first attempt, and a row written before this
 * guard existed carries no digest and is treated as one (there is nothing to compare it to, and
 * refusing would break a retry of a command that already succeeded).
 */
export const assertIdempotentRequest = (input: {
  readonly action: string;
  readonly key: string;
  /** The digest recorded by a previous attempt under this key, or `null` when there was none. */
  readonly previousDigest: string | null;
  readonly digest: string;
}): void => {
  if (input.previousDigest !== null && input.previousDigest !== input.digest) {
    throw new HttpError(
      409,
      'idempotency_key_reused',
      `Idempotency-Key "${input.key}" was already used for a ${input.action} with different arguments; use a new key, or send the request you sent the first time`,
    );
  }
};

/** Reads the previous attempt and refuses a mismatched body; answers this request's digest. */
export const idempotencyGuard = async (
  database: Database,
  input: {
    /** Whose key this is — the scope of the lookup, see the module note. */
    readonly userId: string;
    readonly action: string;
    readonly key: string;
    readonly request: unknown;
  },
): Promise<string> => {
  const digest = configHashOf(input.request);
  const previous = await findIdempotentAttempt(database, {
    userId: input.userId,
    action: input.action,
    key: input.key,
  });
  assertIdempotentRequest({
    action: input.action,
    key: input.key,
    previousDigest: previous?.bodyDigest ?? null,
    digest,
  });
  return digest;
};

/**
 * Has this key already performed this command?
 *
 * `true` means **do nothing and answer the current state**: the `human_actions` row exists, so the
 * command was performed, and the same key with the same body is a retry of it. A different body
 * under the same key never reaches here — {@link assertIdempotentRequest} refuses it first — and a
 * key nobody has used is the first attempt.
 *
 * It is the half of the header the wizard's creates do not need (they have a natural key to
 * re-read) and every task and run command does, because "pause this task" has no row to find.
 */
export const idempotentReplay = async (
  /** How a previous attempt is found — injected, so a route module need name no database. */
  findAttempt: (query: {
    readonly userId: string;
    readonly action: string;
    readonly key: string;
  }) => Promise<{ readonly bodyDigest: string | null; readonly params: JsonObject } | null>,
  input: {
    /** Whose key this is — the scope of the lookup, see the module note. */
    readonly userId: string;
    readonly action: string;
    readonly key: string | null;
    readonly request: unknown;
  },
): Promise<{
  readonly replayed: boolean;
  readonly digest: string | null;
  /** The `params` of the attempt this request replays, so its answer can carry what it made. */
  readonly previous: JsonObject | null;
}> => {
  if (input.key === null) {
    return { replayed: false, digest: null, previous: null };
  }
  const digest = configHashOf(input.request);
  const previous = await findAttempt({
    userId: input.userId,
    action: input.action,
    key: input.key,
  });
  assertIdempotentRequest({
    action: input.action,
    key: input.key,
    previousDigest: previous?.bodyDigest ?? null,
    digest,
  });
  return { replayed: previous !== null, digest, previous: previous?.params ?? null };
};

/**
 * `projects.config_hash` — a digest of a document, over its canonical JSON.
 *
 * It is what `GET …/config` publishes as `hash` and what a later `PUT` may send back as
 * `base_hash`, so the two have to be the same function; it is also what every command digests its
 * request with. Keys are sorted so that a document and the same document with its keys in another
 * order hash alike — a client that round-trips through `JSON.parse` must not be told its
 * configuration moved, and two identical retries must not look like two different requests.
 */
export const configHashOf = (config: unknown): string =>
  createHash('sha256').update(canonicalJson(config)).digest('hex').slice(0, 32);

const canonicalJson = (value: unknown): string => {
  if (Array.isArray(value)) {
    return `[${value.map(canonicalJson).join(',')}]`;
  }
  if (value !== null && typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, entry]) => entry !== undefined)
      .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0));
    return `{${entries.map(([key, entry]) => `${JSON.stringify(key)}:${canonicalJson(entry)}`).join(',')}}`;
  }
  return JSON.stringify(value ?? null);
};
