/**
 * Knowledge base, code map and reports (technical/03 § "Knowledge and code").
 * Mirrors `migrations/0008_knowledge.sql`. Everything here is derived and rebuildable.
 */
import type { JsonObject, JsonValue, MergeRequestRef } from '@platform/contracts';
import { sql } from 'drizzle-orm';
import {
  boolean,
  date,
  integer,
  jsonb,
  numeric,
  pgTable,
  primaryKey,
  real,
  smallint,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';
import { tsvector } from './columns.js';
import {
  knowledgeProposalKindEnum,
  knowledgeProposalSourceEnum,
  knowledgeProposalStatusEnum,
  knowledgeProposalTypeEnum,
} from './enums.js';

const uuidv7 = sql`uuidv7()`;

export const kbDocuments = pgTable('kb_documents', {
  id: uuid('id').primaryKey().default(uuidv7),
  projectId: uuid('project_id').notNull(),
  path: text('path').notNull(),
  commitSha: text('commit_sha'),
  type: text('type'),
  kind: text('kind'),
  status: text('status'),
  confidence: real('confidence'),
  scope: text('scope'),
  paths: text('paths').array().notNull().default(sql`'{}'`),
  trigger: text('trigger'),
  expires: date('expires'),
  lastConfirmed: date('last_confirmed'),
  frontmatter: jsonb('frontmatter').$type<JsonObject>().notNull().default({}),
  contentHash: text('content_hash'),
  tokens: integer('tokens').notNull().default(0),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const kbChunks = pgTable('kb_chunks', {
  id: uuid('id').primaryKey().default(uuidv7),
  documentId: uuid('document_id').notNull(),
  headingPath: text('heading_path'),
  ordinal: integer('ordinal').notNull().default(0),
  text: text('text').notNull(),
  tokens: integer('tokens').notNull().default(0),
  /** Generated by the database. Phase 2 adds `embedding halfvec(1024)` (TD-008, TD-009). */
  search: tsvector('search').generatedAlwaysAs(sql`to_tsvector('simple', "text")`),
});

export const kbLinks = pgTable(
  'kb_links',
  {
    fromDocumentId: uuid('from_document_id').notNull(),
    toPath: text('to_path').notNull(),
    kind: text('kind').notNull(),
    resolvedDocumentId: uuid('resolved_document_id'),
  },
  (table) => [primaryKey({ columns: [table.fromDocumentId, table.toPath, table.kind] })],
);

export const kbProposals = pgTable('kb_proposals', {
  id: uuid('id').primaryKey().default(uuidv7),
  projectId: uuid('project_id').notNull(),
  taskId: uuid('task_id'),
  runId: uuid('run_id'),
  source: knowledgeProposalSourceEnum('source').notNull(),
  kind: knowledgeProposalKindEnum('kind').notNull(),
  type: knowledgeProposalTypeEnum('type').notNull(),
  targetPath: text('target_path').notNull(),
  delta: text('delta').notNull(),
  evidence: jsonb('evidence').$type<JsonValue>().notNull().default([]),
  significance: real('significance').notNull(),
  status: knowledgeProposalStatusEnum('status').notNull().default('scored'),
  decidedBy: uuid('decided_by'),
  decidedAt: timestamp('decided_at', { withTimezone: true }),
  appliedCommitSha: text('applied_commit_sha'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const kbIndexState = pgTable('kb_index_state', {
  projectId: uuid('project_id').primaryKey(),
  commitSha: text('commit_sha'),
  ftsBuiltAt: timestamp('fts_built_at', { withTimezone: true }),
  embeddingsBuiltAt: timestamp('embeddings_built_at', { withTimezone: true }),
  embeddingModel: text('embedding_model'),
});

export const codeFiles = pgTable(
  'code_files',
  {
    projectId: uuid('project_id').notNull(),
    blobSha: text('blob_sha').notNull(),
    path: text('path').notNull(),
    language: text('language'),
    symbols: jsonb('symbols').$type<JsonValue>().notNull().default([]),
  },
  (table) => [primaryKey({ columns: [table.projectId, table.blobSha] })],
);

export const codeMaps = pgTable(
  'code_maps',
  {
    projectId: uuid('project_id').notNull(),
    commitSha: text('commit_sha').notNull(),
    focusHash: text('focus_hash').notNull(),
    tokenBudget: integer('token_budget').notNull(),
    mapText: text('map_text').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [primaryKey({ columns: [table.projectId, table.commitSha, table.focusHash] })],
);

export const readinessEvaluations = pgTable('readiness_evaluations', {
  id: uuid('id').primaryKey().default(uuidv7),
  projectId: uuid('project_id').notNull(),
  level: smallint('level').notNull(),
  criteria: jsonb('criteria').$type<JsonValue>().notNull().default([]),
  evaluatedAt: timestamp('evaluated_at', { withTimezone: true }).notNull().defaultNow(),
  source: text('source').notNull(),
});

/** technical/07 § "Librarian pipeline" step 6, created by migration 0018. */
export const kbHealthReports = pgTable('kb_health_reports', {
  id: uuid('id').primaryKey().default(uuidv7),
  projectId: uuid('project_id').notNull(),
  commitSha: text('commit_sha'),
  documents: integer('documents').notNull().default(0),
  findings: jsonb('findings').$type<JsonValue>().notNull().default([]),
  source: text('source').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const shadowReports = pgTable('shadow_reports', {
  taskId: uuid('task_id').primaryKey(),
  humanMrRef: jsonb('human_mr_ref').$type<MergeRequestRef>(),
  comparison: jsonb('comparison').$type<JsonObject>().notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * One shadow batch — the tickets somebody selected on one day (WP-34, migration 0029).
 *
 * `budgetUsd` is the per-feature cap **as it stood when the batch was created**, copied rather than
 * read back through the settings, so the figure shown beside the batch's actual spend is the one
 * that applied to it.
 */
export const shadowBatches = pgTable('shadow_batches', {
  id: uuid('id').primaryKey().default(uuidv7),
  projectId: uuid('project_id').notNull(),
  requestedBy: uuid('requested_by'),
  budgetUsd: numeric('budget_usd', { precision: 12, scale: 6 }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
});

/**
 * One ticket of a batch. `taskId` is null exactly when `refusedReason` is not (migration 0029's
 * check constraint): Q82 (a) refuses a ticket whose comparison base cannot be resolved rather than
 * running it against today's default branch.
 */
export const shadowBatchTickets = pgTable(
  'shadow_batch_tickets',
  {
    batchId: uuid('batch_id').notNull(),
    ticketKey: text('ticket_key').notNull(),
    taskId: uuid('task_id'),
    baseSha: text('base_sha'),
    humanMrRef: jsonb('human_mr_ref').$type<MergeRequestRef>(),
    humanMrSource: text('human_mr_source'),
    /** product/19 §16's *"to merge"* instant, so the report needs no fourth provider read. */
    humanMrMergedAt: timestamp('human_mr_merged_at', { withTimezone: true }),
    /** How many merged merge requests matched; the report's `notes` states it when it is > 1. */
    humanMrCandidates: integer('human_mr_candidates'),
    refusedReason: text('refused_reason'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [primaryKey({ columns: [table.batchId, table.ticketKey] })],
);

/**
 * One history bootstrap — what the operator asked for and where it got to (WP-35, migration 0030).
 *
 * `capUsd` and `estimatedUsd` are copied at creation for `shadowBatches.budgetUsd`'s reason: the
 * figure shown beside a batch's actual spend has to be the one that applied to it. `mergeRequests`,
 * `batchSize` and `days` travel with them so a reader can re-derive the estimate they were shown.
 */
export const historyBootstrapBatches = pgTable('history_bootstrap_batches', {
  id: uuid('id').primaryKey().default(uuidv7),
  projectId: uuid('project_id').notNull(),
  requestedBy: uuid('requested_by'),
  mergeRequests: integer('merge_requests').notNull(),
  batchSize: integer('batch_size').notNull(),
  days: integer('days').notNull(),
  capUsd: numeric('cap_usd', { precision: 12, scale: 6 }).notNull(),
  estimatedUsd: numeric('estimated_usd', { precision: 12, scale: 6 }).notNull(),
  status: text('status').notNull().default('collecting'),
  detail: text('detail'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
});

/**
 * One mining run of a batch — product/19 §18's *"~20 MRs per Sonnet 5 run"*, as a task.
 *
 * The counts are the platform's record of what the collection put in the sample, kept here rather
 * than derived from `tasks.history_sample` so the batch screen need not read a megabyte of somebody
 * else's review comments. `recordedAt` is what makes `proposals = 0` unambiguous: a run that has
 * reported and found nothing, rather than one that has not reported.
 */
export const historyBootstrapChunks = pgTable('history_bootstrap_chunks', {
  id: uuid('id').primaryKey().default(uuidv7),
  batchId: uuid('batch_id').notNull(),
  chunkIndex: integer('chunk_index').notNull(),
  taskId: uuid('task_id').notNull(),
  mergeRequests: integer('merge_requests').notNull(),
  tickets: integer('tickets').notNull(),
  commits: integer('commits').notNull(),
  redactionCount: integer('redaction_count').notNull().default(0),
  truncated: boolean('truncated').notNull().default(false),
  recordedAt: timestamp('recorded_at', { withTimezone: true }),
  proposals: integer('proposals').notNull().default(0),
  refusedProposals: integer('refused_proposals').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export type KbDocument = typeof kbDocuments.$inferSelect;
export type KbChunk = typeof kbChunks.$inferSelect;
export type KbProposal = typeof kbProposals.$inferSelect;
export type CodeFile = typeof codeFiles.$inferSelect;
export type CodeMap = typeof codeMaps.$inferSelect;
export type ReadinessEvaluation = typeof readinessEvaluations.$inferSelect;
export type KbHealthReport = typeof kbHealthReports.$inferSelect;
export type ShadowReport = typeof shadowReports.$inferSelect;
export type ShadowBatch = typeof shadowBatches.$inferSelect;
export type ShadowBatchTicket = typeof shadowBatchTickets.$inferSelect;
export type HistoryBootstrapBatch = typeof historyBootstrapBatches.$inferSelect;
export type HistoryBootstrapChunk = typeof historyBootstrapChunks.$inferSelect;
