/**
 * Knowledge base, code map and reports (technical/03 § "Knowledge and code").
 * Mirrors `migrations/0008_knowledge.sql`. Everything here is derived and rebuildable.
 */
import type { JsonObject, JsonValue, MergeRequestRef } from '@platform/contracts';
import { sql } from 'drizzle-orm';
import {
  date,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  real,
  smallint,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';
import { tsvector } from './columns.js';
import {
  knowledgeProposalKindEnum,
  knowledgeProposalSourceEnum,
  knowledgeProposalStatusEnum,
  knowledgeProposalTypeEnum,
} from './enums.js';

const uuidv7 = sql`uuidv7()`;

export const kbDocuments = pgTable('kb_documents', {
  id: uuid('id').primaryKey().default(uuidv7),
  projectId: uuid('project_id').notNull(),
  path: text('path').notNull(),
  commitSha: text('commit_sha'),
  type: text('type'),
  kind: text('kind'),
  status: text('status'),
  confidence: real('confidence'),
  scope: text('scope'),
  paths: text('paths').array().notNull().default(sql`'{}'`),
  trigger: text('trigger'),
  expires: date('expires'),
  lastConfirmed: date('last_confirmed'),
  frontmatter: jsonb('frontmatter').$type<JsonObject>().notNull().default({}),
  contentHash: text('content_hash'),
  tokens: integer('tokens').notNull().default(0),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const kbChunks = pgTable('kb_chunks', {
  id: uuid('id').primaryKey().default(uuidv7),
  documentId: uuid('document_id').notNull(),
  headingPath: text('heading_path'),
  ordinal: integer('ordinal').notNull().default(0),
  text: text('text').notNull(),
  tokens: integer('tokens').notNull().default(0),
  /** Generated by the database. Phase 2 adds `embedding halfvec(1024)` (TD-008, TD-009). */
  search: tsvector('search').generatedAlwaysAs(sql`to_tsvector('simple', "text")`),
});

export const kbLinks = pgTable(
  'kb_links',
  {
    fromDocumentId: uuid('from_document_id').notNull(),
    toPath: text('to_path').notNull(),
    kind: text('kind').notNull(),
    resolvedDocumentId: uuid('resolved_document_id'),
  },
  (table) => [primaryKey({ columns: [table.fromDocumentId, table.toPath, table.kind] })],
);

export const kbProposals = pgTable('kb_proposals', {
  id: uuid('id').primaryKey().default(uuidv7),
  projectId: uuid('project_id').notNull(),
  taskId: uuid('task_id'),
  runId: uuid('run_id'),
  source: knowledgeProposalSourceEnum('source').notNull(),
  kind: knowledgeProposalKindEnum('kind').notNull(),
  type: knowledgeProposalTypeEnum('type').notNull(),
  targetPath: text('target_path').notNull(),
  delta: text('delta').notNull(),
  evidence: jsonb('evidence').$type<JsonValue>().notNull().default([]),
  significance: real('significance').notNull(),
  status: knowledgeProposalStatusEnum('status').notNull().default('scored'),
  decidedBy: uuid('decided_by'),
  decidedAt: timestamp('decided_at', { withTimezone: true }),
  appliedCommitSha: text('applied_commit_sha'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const kbIndexState = pgTable('kb_index_state', {
  projectId: uuid('project_id').primaryKey(),
  commitSha: text('commit_sha'),
  ftsBuiltAt: timestamp('fts_built_at', { withTimezone: true }),
  embeddingsBuiltAt: timestamp('embeddings_built_at', { withTimezone: true }),
  embeddingModel: text('embedding_model'),
});

export const codeFiles = pgTable(
  'code_files',
  {
    projectId: uuid('project_id').notNull(),
    blobSha: text('blob_sha').notNull(),
    path: text('path').notNull(),
    language: text('language'),
    symbols: jsonb('symbols').$type<JsonValue>().notNull().default([]),
  },
  (table) => [primaryKey({ columns: [table.projectId, table.blobSha] })],
);

export const codeMaps = pgTable(
  'code_maps',
  {
    projectId: uuid('project_id').notNull(),
    commitSha: text('commit_sha').notNull(),
    focusHash: text('focus_hash').notNull(),
    tokenBudget: integer('token_budget').notNull(),
    mapText: text('map_text').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [primaryKey({ columns: [table.projectId, table.commitSha, table.focusHash] })],
);

export const readinessEvaluations = pgTable('readiness_evaluations', {
  id: uuid('id').primaryKey().default(uuidv7),
  projectId: uuid('project_id').notNull(),
  level: smallint('level').notNull(),
  criteria: jsonb('criteria').$type<JsonValue>().notNull().default([]),
  evaluatedAt: timestamp('evaluated_at', { withTimezone: true }).notNull().defaultNow(),
  source: text('source').notNull(),
});

export const shadowReports = pgTable('shadow_reports', {
  taskId: uuid('task_id').primaryKey(),
  humanMrRef: jsonb('human_mr_ref').$type<MergeRequestRef>(),
  comparison: jsonb('comparison').$type<JsonObject>().notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export type KbDocument = typeof kbDocuments.$inferSelect;
export type KbChunk = typeof kbChunks.$inferSelect;
export type KbProposal = typeof kbProposals.$inferSelect;
export type CodeFile = typeof codeFiles.$inferSelect;
export type CodeMap = typeof codeMaps.$inferSelect;
export type ReadinessEvaluation = typeof readinessEvaluations.$inferSelect;
export type ShadowReport = typeof shadowReports.$inferSelect;
