/**
 * Transcripts (technical/03 § "Transcripts", TD-007, TD-012).
 * Mirrors `migrations/0006_transcripts.sql`.
 */
import type { JsonObject } from '@platform/contracts';
import { sql } from 'drizzle-orm';
import {
  bigint,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';
import { bytea, tsvector } from './columns.js';
import { blobStorageEnum, transcriptKindEnum } from './enums.js';

export const blobs = pgTable('blobs', {
  id: uuid('id').primaryKey().default(sql`uuidv7()`),
  sha256: text('sha256').notNull(),
  size: bigint('size', { mode: 'number' }).notNull(),
  mediaType: text('media_type').notNull(),
  storage: blobStorageEnum('storage').notNull().default('db'),
  locator: text('locator'),
  data: bytea('data'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/** One row per completed SDK message; partial deltas are never stored individually (TD-007). */
export const runMessages = pgTable(
  'run_messages',
  {
    runId: uuid('run_id').notNull(),
    seq: integer('seq').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    kind: transcriptKindEnum('kind').notNull(),
    subtype: text('subtype'),
    parentToolUseId: text('parent_tool_use_id'),
    toolUseId: text('tool_use_id'),
    toolName: text('tool_name'),
    payload: jsonb('payload').$type<JsonObject>().notNull(),
    blobId: uuid('blob_id'),
    searchText: text('search_text'),
    /** Generated by the database; never written by the application. */
    search: tsvector('search').generatedAlwaysAs(
      sql`to_tsvector('simple', coalesce(search_text, ''))`,
    ),
    sizeBytes: integer('size_bytes').notNull().default(0),
    redactionCount: integer('redaction_count').notNull().default(0),
  },
  (table) => [primaryKey({ columns: [table.runId, table.seq, table.createdAt] })],
);

/** Append-only; which redaction rule fired on which message (TD-012). */
export const redactionLog = pgTable('redaction_log', {
  runId: uuid('run_id').notNull(),
  seq: integer('seq').notNull(),
  ruleId: text('rule_id').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export type Blob = typeof blobs.$inferSelect;
export type RunMessage = typeof runMessages.$inferSelect;
export type NewRunMessage = typeof runMessages.$inferInsert;
export type RedactionLogRow = typeof redactionLog.$inferSelect;
